package:
  name: multiqc-mtpercent
  version: "0.0.1"

source:
  fn: multiqc-mtpercent.tar.gz
  url: http://localhost:8080/multiqc-mtpercent.tar.gz
  md5: 4b7fe06ac965040f9243a99bd125af57

build:
  number: 0
  preserve_egg_dir: True
  # multiqc does not support py3k because of click
  skip: true  # [py3k]

requirements:
  build:
    - python
    - setuptools
    - multiqc >=1.2

  run:
    - python
    - multiqc >=1.2

test:
  # Python imports
  imports:
    - multiqc_mtpercent.mtpercent

about:
  home: http://multiqc.info
  license: GNU General Public License v3 (GPLv3)
  summary: 'MultiQC plugin for bcbio report visualization.'
